name: diamond_booking
description: "A new Flutter project."
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+20

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.3
  flutter_native_splash: ^2.4.0
  page_view_indicators: ^2.0.0
  provider: ^6.1.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  google_sign_in: ^6.2.1
  flutter_otp_text_field: ^1.1.3+2
  google_fonts: ^6.2.1
  sizer: ^2.0.15
  image_picker: ^1.1.1
  csc_picker: ^0.2.7
  hijri_picker: ^3.0.0
  firebase_database: ^10.5.4
  flutter_chat_ui: ^1.6.12
  uuid: ^4.4.0
  firebase_storage: ^11.7.4
  open_filex: ^4.4.0
  file_picker: ^8.0.3
  mime: ^1.0.5
  cloud_firestore: ^4.17.2
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.1
  permission_handler: ^11.3.1
  cloud_functions: ^4.7.3
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  country_code_picker: ^3.0.0
  html: ^0.15.4
  pinput: ^4.0.0
  sms_autofill: ^2.3.1
  intl_phone_number_input: ^0.7.4
  timeago: ^3.6.1
  multi_image_picker: ^4.8.01
  badges: ^3.1.2
  camera: ^0.11.0+1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.0
  video_player: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - lib/language/en.json
    - lib/language/ar.json

  fonts:
    - family: CODE_Light
      fonts:
        - asset: assets/fonts/Rantera.otf
          weight: 400
        - asset: assets/fonts/Rantera.otf
          weight: 600
